### ISSUE TITLE
Unable to install perlbrew on Fedora 20

### ISSUE THREAD

**Issue by mannih** [gugod/App-perlbrew#409]
```
curl -kL http://install.perlbrew.pl | bash
...
Can't locate List/Util.pm in @INC (you may need to install the List::Util module)
(@INC contains: FatPacked::39801144=HASH(0x25f5138)
/usr/share/perl5
/usr/lib64/perl5
/usr/local/share/perl5
/usr/local/lib64/perl5)
at perlbrew-25712 line 33.
```
Notice the directories reported to make up `@INC`.

```
perl -V
...
@INC:
    /usr/local/lib64/perl5
    /usr/local/share/perl5
    /usr/lib64/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib64/perl5
    /usr/share/perl5
```

`List::Util` can be found in `/usr/lib64/perl5/vendor_perl`

Obviously, setting up `@INC` leaves out relevant directories.

**Comment by sestaton** [comment]
On Fedora 21, adding vendorlib and vendorarchexp did not solve the issue, but adding '/usr/share/perl5/vendor_perl' to @INC manually solved the issue for me. So, I changed line 3 to: 

    BEGIN { use Config; @INC = @Config{qw(privlibexp archlibexp sitelibexp sitearchexp)}; push @INC, '/usr/share/perl5/vendor_perl'; };

I also installed a couple of modules through the package manager (List::Util and File::Spec, after installing CPAN), but setting the @INC path correctly may be all that is necessary.

**Comment by mvuets** [comment]
I confirm the problem still exists on Fedora 21:
```
$ curl -sL http://install.perlbrew.pl | bash

## Download the latest perlbrew

## Installing perlbrew
Can't locate Getopt/Long.pm in @INC (you may need to install the Getopt::Long module) (@INC contains: FatPacked::21640192=HASH(0x14a3400) /usr/share/perl5 /usr/lib64/perl5 /usr/local/share/perl5 /usr/local/lib64/perl5) at perlbrew-27523 line 33.
BEGIN failed--compilation aborted at perlbrew-27523 line 33.
Compilation failed in require at perlbrew-27523 line 5830.
BEGIN failed--compilation aborted at perlbrew-27523 line 5830.
```

**Comment by markwellis** [comment]
this bit me on centos 7, fixed by following @wumpus's comment above

**Comment by ViktorNacht** [comment]
Here's a one-liner for installing onto CentOS 7. Self-Upgrade still fails, use at your own risk. I needed it for a deployment script, plus it was fun. :) Probably very brittle to changes in the source.

`curl -kL http://install.perlbrew.pl | sed "/\$PERLBREWDOWNLOAD/{N;s|$|sed -i -r '/@INC/ s/([)][}])/ vendorlib vendorarch\\\1/' \\\$LOCALINSTALLER\n|}" | bash`

As a Gist: https://gist.github.com/ViktorNacht/56ae6617734f28e2b1b3

**Comment by nnutter** [comment]
As pointed out installation is broken on Fedora 21.  `Getopt::Long`, `File::Path`, and `Pod::Usage` all need to come from `vendorlibexp`.  I hacked things on my [fork][1] to get everything through.  Hopefully you can use it to make a reasonable patch.

```
$ ( export PERLBREWURL=https://github.com/nnutter/App-perlbrew/raw/develop/perlbrew; \curl -L http://install.perlbrew.pl | \bash )
...
## Done.
$ source ~/.perlbrew/etc/bashrc
$ perlbrew --version
/home/nnutter/.perlbrew/bin/perlbrew  - App::perlbrew/0.73
```

```
$ perl -MConfig -MFile::Path -MPod::Usage -MGetopt::Long -e 'print join(qq(\n), @INC{qw(Pod/Usage.pm Getopt/Long.pm File/Path.pm)}, $Config{vendorlibexp}), qq(\n)'
/usr/share/perl5/vendor_perl/Pod/Usage.pm
/usr/share/perl5/vendor_perl/Getopt/Long.pm
/usr/share/perl5/vendor_perl/File/Path.pm
/usr/share/perl5/vendor_perl
```

[1]: https://github.com/gugod/App-perlbrew/compare/develop...nnutter:develop

**Comment by sestaton** [comment]
The command @nnutter posted above will install perlbrew without any modifications on Fedora now, but the `self-upgrade` command is still broken (similar to other solutions posted). It looks like that method calls `self-install` which is using the system Perl and customizing the shebang to the system PATH (I think), so you still get:

    Can't locate Getopt/Long.pm in @INC ...

I guess a fix would have to involve the code in those upgrade/install methods, or elsewhere, to extend the include PATH somehow.

**Comment by zdm** [comment]
+1
When this patch will be added and released?

**Comment by nnutter** [comment]
@zdm My "fix" is a crappy hack and not something they can merge.

**Comment by zdm** [comment]
I understand.
I think, this is not so complex to add vendorlib and vendorarchexp to the several places in code.
This is critical bug, perlbrew doesn't work under very popular centos at all.
What was the reason to ignore vendor libs?

**Comment by gugod** [comment]
There was intention to exclude vendorlib -- perlbrew really is merely just a collection of system-specific hacks. Unfortunately, most of them being OSX, and some being Debian/Ubuntu.

The `BEGIN { @INC }`  block is another hack to mainly ensure that the "system" Cwd.pm is loaded, assuming "perlbrew" is executed by "system" perl. This way, when PERL5LIB contains some packages that are binary-incompatible with system perl, perlbrew can still work.

It surprises me that there are many issues around it that are effected by how different OS package perl.

**Comment by Grinnz** [comment]
Any idea about a better solution for this? (It is still a problem for Fedora 22, and obviously RHEL7) I am fine manually editing the perlbrew script myself, but it is not very user-friendly.

**Comment by gugod** [comment]
The commit d38951b713e61dfda124b0bd59783522044c793b I just pushed modify the fatpacking script. The fatpacked perlbrew executable will be OK in future releases.

**Comment by Grinnz** [comment]
Thank you for the update, but it isn't quite a complete solution for Fedora 22. (I don't have a RHEL7 system to test at the moment)

1. for some reason, vendorlibexp (and vendorarchexp) must go at the end, or there is an error about Config_heavy.pl. I think it is that privlibexp must remain the first item.
2. vendorarchexp must also be included, otherwise File::Spec is not found.

**Comment by Grinnz** [comment]
Sorry, I think I misinterpreted, this is to fatpack those modules into the script. So then it would just need to make sure that Getopt::Long and File::Spec and any other required modules in those directories end up fatpacked.

**Comment by sestaton** [comment]
I just tested on Fedora 22 and CentOS 7, and adding vendorlib and vendorarchexp to line 3 did the trick. @wumpus metioned this before, I don't know how I missed it or didn't get that right. If the self-upgrade pulls the latest fatpacked file then that command wouldn't work unless it includes these changes (I think). Thanks for the work on this.

**Comment by gugod** [comment]
FYI for those who are interested to do some pre-flight testing, I rebuild the fatpacked 'perlbrew' executable in develop branch:

    https://raw.githubusercontent.com/gugod/App-perlbrew/develop/perlbrew

Just download and replace the current perlbrew executable (usually located under  `~/perl5/perlbrew/bin`)

**Comment by Grinnz** [comment]
I tried it but I got the same Config_heavy.pl error as when I put vendorlibexp first in my local copy:
```
Can't locate Config_heavy.pl in @INC (@INC contains:) at /usr/lib64/perl5/Config.pm line 80.
BEGIN failed--compilation aborted at ./perlbrew.pl line 3.
```
I think that moving vendorlibexp to the end and adding vendorarchexp will also be required after all.

**Comment by sestaton** [comment]
I got the same error as above about Config_heavy.pl. If I fall back to what was in place previously and simply add the vendor libs we've been discussing, i.e.,

    BEGIN { use Config; @INC = @Config{qw(privlibexp archlibexp sitelibexp sitearchexp vendorlib vendorarchexp)} };

It seems to install just fine. Hope that helps.

**Comment by malkowski** [comment]
Thought I'd throw in a couple more pennies to the discussion: I made the following changes to the perlbrew script to get things working in RHEL7:

<pre>BEGIN { use Config; @INC = @Config{qw( privlibexp archlibexp sitelibexp sitearchexp vendorlib vendorarchexp vendorlibexp )} };</pre>

**Comment by czarekplpl** [comment]
On Centos 7 I got the error in the last line:
perlbrew is installed: ~/perl5/perlbrew/bin/perlbrew
perlbrew root (~/perl5/perlbrew) is initialized.
Append the following piece of code to the end of your ~/.bash_profile and start a
new shell, perlbrew should be up and fully functional from there:
    source ~/perl5/perlbrew/etc/bashrc
Simply run `perlbrew` for usage details.
Happy brewing!

ERROR: Failed to retrieve patchperl executable.

**Comment by dhoer** [comment]
+1
When this patch will be added and released?

**Comment by davemenninger** [comment]
:+1:

**Comment by karenetheridge** [comment]
Looks to be released in 0.74: https://metacpan.org/changes/distribution/App-perlbrew

**Comment by Grinnz** [comment]
This version seems to solve the issue on Fedora 22.

**Comment by nnutter** [comment]
Worked on Fedora 23.

**Comment by wumpus** [comment]
Needs to also be tested in rhel/centos-5/6/7... glad to see this finally getting somewhere!

**Comment by Grinnz** [comment]
I believe this was actually fixed (for the fatpack version) by this commit. https://github.com/gugod/App-perlbrew/commit/3dcb86db0205294806f0f6d3e581a2e75fb361cb

**Comment by dhoer** [comment]
CentOS release 6.7 (Final) and CentOS Linux release 7.1.1503 (Core) worked. Thanks.

**Comment by gugod** [comment]
Thanks everyone for the feedback and fixes. Let's have some virtual beer together:

:beers: :beer: :beers: :beer: :beers: :beer: :beers: :beer:
