### ISSUE TITLE
available command is not working properly anymore

### ISSUE THREAD

**Issue by glasswalk3r** [gugod/App-perlbrew#620]
Something is broken and looks like is due some website change at [CPAN website](https://www.cpan.org/src/README.html):

```
alceu@yggdrasil:~/Projetos/cpan-openbsd-smoker/vagrant/scripts$ perlbrew version
/home/alceu/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.82
alceu@yggdrasil:~/Projetos/cpan-openbsd-smoker/vagrant/scripts$ perlbrew available

  cperl-5.22.5  available from  <https://github.com/perl11/cperl/archive/cperl-5.22.5.tar.gz>
  cperl-5.24.3  available from  <https://github.com/perl11/cperl/archive/cperl-5.24.3.tar.gz>
  cperl-5.26.2  available from  <https://github.com/perl11/cperl/archive/cperl-5.26.2.tar.gz>
  cperl-5.27.2  available from  <https://github.com/perl11/cperl/archive/cperl-5.27.2.tar.gz>
```

Taking a look at the code, `perlbrew` is using `curl` and parsing the HTML with regular expressions. I'm willing to try and provide a PR, but the current implementation is basically a hack.

I suggest taking this to the CPAN website maintainers and providing a file that can actually be parsed and providing deterministic results, in other words, YAML, JSON or even XML (in worst case scenarios).

That would avoid issues in the long way, when somebody decide that is time to give the CPAN website a new face.

Just please let me know if you think the suggestion is good.

**Comment by gugod** [comment]
related to #617 and already fixed in latest perlbrew for the moment.

**Comment by glasswalk3r** [comment]
Did a quick test here:

```
alceu@yggdrasil:~/Projetos/cpan-openbsd-smoker/vagrant/scripts$ perlbrew self-upgrade
perlbrew is installed: ~/perl5/perlbrew/bin/perlbrew
perlbrew root (~/perl5/perlbrew) is initialized.
alceu@yggdrasil:~/Projetos/cpan-openbsd-smoker/vagrant/scripts$ perlbrew version
/home/alceu/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.83
alceu@yggdrasil:~/Projetos/cpan-openbsd-smoker/vagrant/scripts$ perlbrew available

  cperl-5.22.5   
  cperl-5.24.3   
  cperl-5.26.2   
  cperl-5.27.2   
```
I'm still not seeing any other perls available. Do I need to restart my user session or something like that?

**Comment by gugod** [comment]
@glasswalk3r oops, sorry. I was meant to say "the perlbrew in deveop branch" instead of "latest perlbrew". I'm making a new release at the moment too. When it is finished, do another `self-upgrade` and this issue should be fixed.

**Comment by gugod** [comment]
For future refernce, perhaps it is a more stable option to query metacpan api to retrieve a list of perl r release in `availble` command. (we already use metacpan api to get the download_url.)

Here's to get the 25 most recent releases (not necessarily the one with largest versions)

    curl --silent 'https://fastapi.metacpan.org/v1/release/_search?size=25&sort=date:desc&q=distribution.lowercase:perl'

It is, however, very different then what's enumerated in the [cpan README.html](https://www.cpan.org/src/README.html) page.

**Comment by gugod** [comment]
The fix is released in 0.84.
